openapi: 3.0.3
info:
  title: Monitoring Service Api
  description: API for monitoring service, which is connected to the monitoring bot
  version: 0.0.1
tags:
  - name: Monitoring
    description: Main monitoring api
paths:
  /action:
    post:
      tags:
        - Monitoring
      description: send alert
      operationId: alert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        '200':
          description: Successful Received
        '400':
          description: Bad Request
        '500':
          description: Internal Error

components:
  schemas:
    Action:
      type: object
      properties:
        type:
          type: string
          enum:
          - sql
          - 
        body:
          type: object
